name: Action on Pull Request to generate Kong Config from Spec and Validate it

on:
  pull_request:
    branches:
      - master

jobs:
  deploy_to_kong:
    runs-on: self-hosted
    name: Generate Kong config from Spec and Validate config
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Kong declarative configuration from Spec
        #name for insomnia file not for real-life usage: spc_d95de7ad75f04714a033d9e6544caea4.yml
        run: inso generate config .insomnia/ApiSpec/spc_d95de7ad75f04714a033d9e6544caea4.yml.yaml --type declarative > kong.yaml
      - name: Validate Kong declarative configuration
        run: deck validate
