name: Action on Pull Request to generate Kong Config from Spec and Validate it

on:
  pull_request:
    branches:
      - master

jobs:
  deploy_to_kong:
    runs-on: self-hosted
    name: Generate Kong config from Spec and Validate config
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Kong declarative configuration from Spec
        run: inso generate config ./openapi/uuid-generator.yaml --type declarative > kongV2.yaml
      - name: Convert the spec from v2 into v3
        run: deck convert --from kong-gateway-2.x --to kong-gateway-3.x --input-file kongV2.yaml --output-file kong.yaml
      - name: Validate Kong declarative configuration
        run: deck validate
